// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uhxyflpcoldfaxyxesyf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVoeHlmbHBjb2xkZmF4eXhlc3lmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NjEzMjAsImV4cCI6MjA2OTUzNzMyMH0.rKYwcpq6XaoJA_9OOjZmtK2jk96y4h6anyY330tX1iw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});